name: Handle updated vocabs
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo
        uses: actions/checkout@v1
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: Set up SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{secrets.KEY}}"  > /home/runner/.ssh/key.pem
          chmod 400 /home/runner/.ssh/key.pem
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','     
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1   
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_HOST_IP: ${{secrets.DB_HOST_IP}}
            KEY: ${{secrets.KEY}}
            SSH_USER: ${{secrets.SSH_USER}}
        run: |
          echo 'create tunnel'
          ssh  -N  -i /home/runner/.ssh/key.pem -o StrictHostKeyChecking=no "$SSH_USER@$DB_HOST_IP" -L 127.0.0.1:3040:localhost:3030 &
          jobs -l
          curl localhost:3040
          curl 127.0.0.1:3040
          exit 0
          echo 'test connection'
          wget 127.0.0.1:3040/index.html -O test
          cat test
          echo 'Run update script...'
          a=${{steps.file_changes.outputs.files_added}}
          m=${{steps.file_changes.outputs.files_modified}}
          d=${{steps.file_changes.outputs.files_removed}}
          r=${{steps.file_changes.outputs.files_renamed}}
          if [ -z $a ]; then a="x"; fi
          if [ -z $m ]; then m="x"; fi
          if [ -z $d ]; then d="x"; fi
          if [ -z $r ]; then r="x"; fi
          echo 'update'
          python scripts/update_vocabs.py -a $a -m $m -d $d -r $r
          exit 0

