name: Handle updated vocabs
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo
        uses: actions/checkout@v1
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: Set up SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{secrets.KEY}}"  > /home/runner/.ssh/key.pem
          chmod 400 /home/runner/.ssh/key.pem
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','     
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_DATASET: ${{secrets.DB_DATASET}}
        run: |
          echo 'create tunnel'
          ssh  -N  -i /home/runner/.ssh/key.pem -o StrictHostKeyChecking=no "${{secrets.SSH_USER}}@${{secrets.DB_HOST_IP}}" -L localhost:3030:localhost:3030 &
          sleep 5
          echo 'test'
          wget localhost:3030/nerc-test -O output.html && cat output.html
          echo 'Run update script...'
          a=${{steps.file_changes.outputs.files_added}}
          m=${{steps.file_changes.outputs.files_modified}}
          d=${{steps.file_changes.outputs.files_removed}}
          r=${{steps.file_changes.outputs.files_renamed}}
          if [ -z $a ]; then a="x"; fi
          if [ -z $m ]; then m="x"; fi
          if [ -z $d ]; then d="x"; fi
          if [ -z $r ]; then r="x"; fi
          python scripts/update_vocabs.py -a $a -m $m -d $d -r $r
